#!/bin/bash
cd ../edk2
. ../edk2/edksetup.sh
build -b DEBUG -p i915ovmfPkg/i915ovmf.dsc || exit
cd ../i915_simple
#cp ../edk2/Build/i915ovmf/RELEASE_GCC5/X64/i915ovmf.efi ./ || exit
cp ../edk2/Build/i915ovmf/DEBUG_GCC5/X64/i915ovmf.rom ./ || exit

if [ -e /sys/bus/pci/devices/0000:00:02.0/2aee154e-7d0d-11e8-88b8-6f45320c7162 ]
then
	true
else
	modprobe kvmgt || exit
	echo 2aee154e-7d0d-11e8-88b8-6f45320c7162 > /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create || exit
fi

mkdir -p tmpfat
mount ../uefi_fun/disk tmpfat
mkdir -p tmpfat/EFI/BOOT
cp shutdown.efi tmpfat/EFI/BOOT/BOOTX64.EFI
umount tmpfat
rmdir tmpfat

~/gpdvm/bin/qemu-system-x86_64 -k en-us -name uefitest,debug-threads=on -serial stdio -m 2048 -M pc -cpu host -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -machine kernel_irqchip=on -nodefaults -rtc base=localtime,driftfix=slew -no-hpet -global kvm-pit.lost_tick_policy=discard -enable-kvm -bios /home/hqm/gpdvm/bin/ovmf.fd --display egl-headless,gl=es -vga none -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/2aee154e-7d0d-11e8-88b8-6f45320c7162,addr=02.0,display=on,x-igd-opregion=on,romfile=`pwd`/i915ovmf.rom -device qemu-xhci,p2=8,p3=8 -device usb-kbd -device usb-tablet -drive format=raw,file=../uefi_fun/disk

#~/gpdvm/bin/qemu-system-x86_64 -k en-us -name uefitest,debug-threads=on -serial stdio -m 2048 -M pc -cpu host -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -machine kernel_irqchip=on -nodefaults -rtc base=localtime,driftfix=slew -no-hpet -global kvm-pit.lost_tick_policy=discard -enable-kvm -bios /home/hqm/gpdvm/bin/ovmf.fd -display gtk,gl=es,grab-on-hover=on -full-screen -vga none -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/2aee154e-7d0d-11e8-88b8-6f45320c7162,addr=02.0,display=on,x-igd-opregion=on,romfile=`pwd`/i915ovmf.rom -device qemu-xhci,p2=8,p3=8 -device usb-kbd -device usb-tablet -drive format=raw,file=../uefi_fun/disk
